- name: ${SND1_CLUSTER_NAME}
  url: ${SND1_CLUSTER_API_SERVER_ADDRESS}
  authProvider: azure
  skipTLSVerify: true
  skipMetricsLookup: true
- name: ${SND2_CLUSTER_NAME}
  url: ${SND2_CLUSTER_API_SERVER_ADDRESS}
  authProvider: azure
  skipTLSVerify: true
  skipMetricsLookup: true
- name: ${SND3_CLUSTER_NAME}
  url: ${SND3_CLUSTER_API_SERVER_ADDRESS}
  authProvider: azure
  skipTLSVerify: true
  skipMetricsLookup: true
# - name: ${DEV1_CLUSTER_NAME}
#   url: ${DEV1_CLUSTER_API_SERVER_ADDRESS}
#   authProvider: azure
#   skipTLSVerify: true
#   skipMetricsLookup: true
# - name: ${TST1_CLUSTER_NAME}
#   url: ${TST1_CLUSTER_API_SERVER_ADDRESS}
#   authProvider: azure
#   skipTLSVerify: true
#   skipMetricsLookup: true
# - name: ${TST2_CLUSTER_NAME}
#   url: ${TST2_CLUSTER_API_SERVER_ADDRESS}
#   authProvider: azure
#   skipTLSVerify: true
#   skipMetricsLookup: true        
# - name: ${PRE1_CLUSTER_NAME}
#   url: ${PRE1_CLUSTER_API_SERVER_ADDRESS}
#   authProvider: azure
#   skipTLSVerify: true
#   skipMetricsLookup: true
# - name: ${PRD1_CLUSTER_NAME}
#   url: ${PRD1_CLUSTER_API_SERVER_ADDRESS}
#   authProvider: azure
#   skipTLSVerify: true
#   skipMetricsLookup: true  
