default:
  tenantId: ${AUTH_MICROSOFT_TENANT_ID}
  queryMode: advanced
  user:
    select: ['id', 'mail', 'displayName', 'description', 'userPrincipalName']
    loadPhotos: false
    filter: not(startsWith(userPrincipalName, 'a-')) and (endsWith(userPrincipalName, 'defra.gov.uk') or endsWith(userPrincipalName, 'defra.onmicrosoft.com'))
  group:
    filter: "displayName eq '${ADP_PORTAL_PLATFORM_ADMINS_GROUP}' or startsWith(displayName, '${ADP_PORTAL_USERS_GROUP_PREFIX}')"
  schedule:
    frequency: { hours: 0, minutes: 35 }
    timeout: { minutes: 10 }
