services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
