http_interactions:
  - request:
      method: GET
      path: /
      headers:
        host: localhost:3001
        connection: keep-alive
        sec-ch-ua: '"Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"'
        sec-ch-ua-mobile: '?0'
        sec-ch-ua-platform: '"macOS"'
        upgrade-insecure-requests: '1'
        user-agent: >-
          Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
          (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
        accept: >-
          text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        sec-fetch-site: none
        sec-fetch-mode: navigate
        sec-fetch-user: '?1'
        sec-fetch-dest: document
        accept-encoding: gzip, deflate, br, zstd
        accept-language: en-US,en;q=0.9,es;q=0.8
        cookie: >-
          csrftoken=FYOnl4ZK68j8KBbakli8orD7TCVAWd2o; preferred_color_mode=dark;
          _octo=GH1.1.1838677461.1714058581; tz=Europe%2FLondon;
          _gh_sess=7xiAbtbds%2BRnHYlVrYvqysjwp8vo%2FZ42Yf4TTinGxfpsVmZS0r7epfov27uiE8pUnWdYj7Wb0LUTdjg4DhRUVeIDKVvCAXod%2BUwSldJNvnvRqSX4%2FJHW5dNJo3xXIrXVIBiJ61rM75KfR3Cv0g2SgfgBp82dNwdkgiczn3Bpma0Nk9pMRCZT2WXjVHuPWgQSzaEqGJiYqQxiflRTDEL8jSSKlidMsKy7YdYQuR4pQvrxkSE4xdRCPlDQBKB0L3PqpmbFKFKzRgyEK4wp3qXmbRbkObscl3LRVm6uR9rh5eDgGqTM--6uMg5NH3ERQDD1KE--7TJejjGM7KGjEps5GF%2FLIA%3D%3D
      body:
        encoding: utf8
        data: ''
        compression: none
    response:
      status:
        code: 200
      headers:
        server: GitHub.com
        date: Thu, 25 Apr 2024 15:35:00 GMT
        content-type: application/json; charset=utf-8
        cache-control: public, max-age=60, s-maxage=60
        vary: Accept, Accept-Encoding, Accept, X-Requested-With
        etag: W/"d1b33bb9cc51fd639d6db1d726fd56f6d661a0568d0ff32b543a69a738014479"
        x-github-media-type: unknown, github.v3
        x-github-api-version-selected: '2022-11-28'
        access-control-expose-headers: >-
          ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit,
          X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource,
          X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes,
          X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO,
          X-GitHub-Request-Id, Deprecation, Sunset
        access-control-allow-origin: '*'
        strict-transport-security: max-age=31536000; includeSubdomains; preload
        x-frame-options: deny
        x-content-type-options: nosniff
        x-xss-protection: '0'
        referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
        content-security-policy: default-src 'none'
        content-encoding: gzip
        x-ratelimit-limit: '60'
        x-ratelimit-remaining: '59'
        x-ratelimit-reset: '1714062900'
        x-ratelimit-resource: core
        x-ratelimit-used: '1'
        accept-ranges: bytes
        content-length: '530'
        x-github-request-id: F7DE:4CAB7:407A1E:41DA08:662A7824
      body:
        encoding: utf8
        data: |
          {
            "current_user_url": "https://api.github.com/user",
            "current_user_authorizations_html_url": "https://github.com/settings/connections/applications{/client_id}",
            "authorizations_url": "https://api.github.com/authorizations",
            "code_search_url": "https://api.github.com/search/code?q={query}{&page,per_page,sort,order}",
            "commit_search_url": "https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}",
            "emails_url": "https://api.github.com/user/emails",
            "emojis_url": "https://api.github.com/emojis",
            "events_url": "https://api.github.com/events",
            "feeds_url": "https://api.github.com/feeds",
            "followers_url": "https://api.github.com/user/followers",
            "following_url": "https://api.github.com/user/following{/target}",
            "gists_url": "https://api.github.com/gists{/gist_id}",
            "hub_url": "https://api.github.com/hub",
            "issue_search_url": "https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}",
            "issues_url": "https://api.github.com/issues",
            "keys_url": "https://api.github.com/user/keys",
            "label_search_url": "https://api.github.com/search/labels?q={query}&repository_id={repository_id}{&page,per_page}",
            "notifications_url": "https://api.github.com/notifications",
            "organization_url": "https://api.github.com/orgs/{org}",
            "organization_repositories_url": "https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}",
            "organization_teams_url": "https://api.github.com/orgs/{org}/teams",
            "public_gists_url": "https://api.github.com/gists/public",
            "rate_limit_url": "https://api.github.com/rate_limit",
            "repository_url": "https://api.github.com/repos/{owner}/{repo}",
            "repository_search_url": "https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}",
            "current_user_repositories_url": "https://api.github.com/user/repos{?type,page,per_page,sort}",
            "starred_url": "https://api.github.com/user/starred{/owner}{/repo}",
            "starred_gists_url": "https://api.github.com/gists/starred",
            "topic_search_url": "https://api.github.com/search/topics?q={query}{&page,per_page}",
            "user_url": "https://api.github.com/users/{user}",
            "user_organizations_url": "https://api.github.com/user/orgs",
            "user_repositories_url": "https://api.github.com/users/{user}/repos{?type,page,per_page,sort}",
            "user_search_url": "https://api.github.com/search/users?q={query}{&page,per_page,sort,order}"
          }
        compression: gzip
