version: "3.5"

services:
  editor:
    build: editor
    init: true
    env_file:
      - ../.env

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

