parameters:
  - name: deployFromFeature
    displayName: 'Deploy from Feature Branch'
    type: boolean
    default: false
  - name: deployConfigOnly
    displayName: 'Deploy App Config'
    type: boolean
    default: false
pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      #ref: main
      ref: rv/400703

extends:
  template: /pipelines/common-aca-app-build.yaml@DEFRA-ADPPipelineCommon
  parameters:
    deployFromFeature: ${{ parameters.deployFromFeature }}
    programmeName: 'adp'
    appName: 'adp-portal-web'
    privateAgentName: ''
    deployConfigOnly: ${{ parameters.deployConfigOnly }}
    appBuildConfig:
      appFrameworkType: 'nodejs'
      projectPath: './package.json'
      imageRepoName: 'adp-portal'
      dockerfilePath: './packages/backend/Dockerfile'
      snykPolicyFilePath: './packages/backend/.snyk'
      appPath: '/'      
    appDeployConfig:
      filepath: '.azuredevops/backstage.yaml'
      variableGroups:
        - adp-portal-web-<environment>
    appTestConfig:
      testEnvVariables: 
        - name: E2E_TEST_ACCOUNTS_ADPTESTUSER1_EMAIL
          value: E2E-TEST-ACCOUNTS-ADPTESTUSER1-EMAIL
        - name: E2E_TEST_ACCOUNTS_ADPTESTUSER1_PASSWORD
          value: E2E-TEST-ACCOUNTS-ADPTESTUSER1-PASSWORD
        - name: E2E_TEST_ACCOUNTS_ADPTESTUSER2_EMAIL
          value: E2E-TEST-ACCOUNTS-ADPTESTUSER2-EMAIL
        - name: E2E_TEST_ACCOUNTS_ADPTESTUSER2_PASSWORD
          value: E2E-TEST-ACCOUNTS-ADPTESTUSER2-PASSWORD
        - name: E2E_TEST_ACCOUNTS_ADPTESTUSER3_EMAIL
          value: E2E-TEST-ACCOUNTS-ADPTESTUSER3-EMAIL
        - name: E2E_TEST_ACCOUNTS_ADPTESTUSER3_PASSWORD
          value: E2E-TEST-ACCOUNTS-ADPTESTUSER3-PASSWORD
        - name: E2E_TEST_ACCOUNTS_ADPTESTUSER4_EMAIL
          value: E2E-TEST-ACCOUNTS-ADPTESTUSER4-EMAIL
        - name: E2E_TEST_ACCOUNTS_ADPTESTUSER4_PASSWORD
          value: E2E-TEST-ACCOUNTS-ADPTESTUSER4-PASSWORD
        - name: E2E_TEST_ACCOUNTS_ADPTESTUSER5_EMAIL 
          value: E2E-TEST-ACCOUNTS-ADPTESTUSER5-EMAIL
        - name: E2E_TEST_ACCOUNTS_ADPTESTUSER5_PASSWORD
          value: E2E-TEST-ACCOUNTS-ADPTESTUSER5-PASSWORD
