parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: true
  - name: deployConfigOnly
    displayName: "Deploy App Config"
    type: boolean
    default: true
pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: refs/heads/rv/323021

extends:
  template: /pipelines/common-aca-app-build.yaml@DEFRA-ADPPipelineCommon
  parameters:
    deployFromFeature: ${{ parameters.deployFromFeature }}
    deployConfigOnly: ${{ parameters.deployConfigOnly }}
    privateAgentName: ''
    containerAppName: 'ssvadpinfca3401-portal-web'
    appName: 'adp-portal'
    appBuildConfig:
      appFrameworkType: "nodejs"  
      projectPath: "./package.json"
      imageRepoName: "adp-portal"
      appPath: "/app"
      dockerfilePath: "./packages/backend/Dockerfile"
      snykPolicyFilePath: "./packages/backend/.snyk"
    appDeployConfig:
      filepath: ".azuredevops/backstage.yaml"  
      variableGroups:
        - adp-portal-ssv3
        - adp-portal-ssv5
      variables:      
        - ADP-PORTAL-*
