parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - "main"
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: refs/heads/main

extends:
  template: /pipelines/common-portal-app-build.yaml@DEFRA-ADPPipelineCommon
  parameters:
    serviceName: "backstage"
    deployFromFeature: ${{ parameters.deployFromFeature }}
    appBuildConfig:
      imageRepoName: "adp-portal"
    appDeployConfig:
      filepath: ".azuredevops/backstage.yaml"  
      variableGroups:
        - adp-portal-ssv3
        - adp-portal-ssv5
      variables:      
        - ADO-ORGANIZATION
        - ADO-PAT
        - ADP-PORTAL-PLATFORM-ADMINS-GROUP
        - ADP-PORTAL-PROGRAMME-ADMINS-GROUP
        - ADP-PORTAL-USERS-GROUP
        - BACKSTAGE-BACKEND-SECRET
        - BACKEND-PLUGINS-SECRET
        - GITHUB-APP-ID
        - GITHUB-CLIENT-ID
        - GITHUB-CLIENT-SECRET
        - GITHUB-PRIVATE-KEY
        - GRAFANA-ENDPOINT
        - GRAFANA-TOKEN
        - SND1-CLUSTER-NAME
        - SND1-CLUSTER-API-SERVER-ADDRESS
        - SND2-CLUSTER-NAME
        - SND2-CLUSTER-API-SERVER-ADDRESS
        - SND3-CLUSTER-NAME
        - SND3-CLUSTER-API-SERVER-ADDRESS
        - DEV1-CLUSTER-NAME
        - DEV1-CLUSTER-API-SERVER-ADDRESS
        - TST1-CLUSTER-NAME
        - TST1-CLUSTER-API-SERVER-ADDRESS
        - TST2-CLUSTER-NAME
        - TST2-CLUSTER-API-SERVER-ADDRESS
        - PRE1-CLUSTER-NAME
        - PRE1-CLUSTER-API-SERVER-ADDRESS
        - PRD1-CLUSTER-NAME
        - PRD1-CLUSTER-API-SERVER-ADDRESS
